print("MUD-MASH is a text based game, You can use the following text commands to proceed in the game.")
print("\nLocation -- Use this command to get details about the location")
print("L -- Use this command to get details about the location")
print("Go North -- Use this command to move towards north direction")
print("GN -- Use this command to move towards north direction")
print("Go South -- Use this command to move towards south direction")
print("GS -- Use this command to move towards south direction")
print("Go East -- Use this command to move towards East direction")
print("GE -- Use this command to move towards East direction")
print("Go West -- Use this command to move towards West direction")
print("GW -- Use this command to move towards West direction")
print("Quit -- Use this command to quit the game.")
print("Q-- Use this command to quit the game.")
